server:
  port: 9003

spring:
  application:
    name: credit-service

  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置sentinel 控制台地址
        dashboard: 127.0.0.1:8080

feign:
  sentinel:
    #启动sentinel对feign的支持
    enabled: true
